SELECT
    CASE WHEN GROUP_CONCAT(NAME) LIKE '%Python%' AND GROUP_CONCAT(CATEGORY) LIKE '%Front%' THEN 'A'
         WHEN GROUP_CONCAT(NAME) LIKE '%C#%' THEN 'B'
         WHEN GROUP_CONCAT(CATEGORY) LIKE '%Front%' THEN 'C'
        END AS GRADE, ID, MAX(EMAIL) AS EMAIL
FROM DEVELOPERS D LEFT JOIN SKILLCODES S ON(D.SKILL_CODE & S.CODE = S.CODE)
GROUP BY ID
HAVING GRADE IS NOT NULL
ORDER BY 1, 2
