WITH USER21 AS (
    SELECT USER_ID
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021
)

SELECT
    YEAR(O.SALES_DATE) AS YEAR,
    MONTH(O.SALES_DATE) AS MONTH,
    COUNT(DISTINCT USER_ID) AS PURCHASED_USERS,
    ROUND(
        COUNT(DISTINCT O.USER_ID)
        / (SELECT COUNT(*) FROM USER21),
        1
    ) AS PURCHASED_RATIO
FROM ONLINE_SALE O JOIN USER21 U USING(USER_ID)
GROUP BY 1, 2
ORDER BY 1, 2
