SELECT CAR_ID, CAR_TYPE, ROUND(DAILY_FEE * (100 - DISCOUNT_RATE)/100 * 30) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P USING(CAR_TYPE)
WHERE CAR_TYPE IN('세단', 'SUV')
  AND CAR_ID NOT IN(
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE DATE_FORMAT(START_DATE, '%Y-%m-%d') <= '2022-11-30'
      AND DATE_FORMAT(END_DATE, '%Y-%m-%d') >= '2022-11-01'
) AND DURATION_TYPE LIKE '%30일 이상'
HAVING FEE >= 500000 AND FEE < 2000000
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC
