SELECT P.PRODUCT_ID AS PRODUCT_ID, PRODUCT_NAME AS PRODUCT_NAME, SUM(P.PRICE*O.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT P JOIN FOOD_ORDER O USING(PRODUCT_ID)
WHERE PRODUCE_DATE >= '2022-05-01'
  AND PRODUCE_DATE <  '2022-06-01'
GROUP BY PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID
