WITH TRUCK_DURATION AS (
    SELECT
        H.HISTORY_ID,
        C.DAILY_FEE,
        DATEDIFF(H.END_DATE, H.START_DATE) + 1 AS RENT_DAYS,
        CASE
            WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 90 THEN '90일 이상'
            WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 30 THEN '30일 이상'
            WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 7 THEN '7일 이상'
            ELSE NULL
        END AS DURATION_TYPE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
    JOIN CAR_RENTAL_COMPANY_CAR AS C
        ON H.CAR_ID = C.CAR_ID
    WHERE C.CAR_TYPE = '트럭'
)
SELECT
    TD.HISTORY_ID,
    ROUND(TD.DAILY_FEE * TD.RENT_DAYS * (100 - IFNULL(P.DISCOUNT_RATE, 0)) / 100) AS FEE
FROM TRUCK_DURATION AS TD
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS P
    ON TD.DURATION_TYPE = P.DURATION_TYPE
    AND P.CAR_TYPE = '트럭'
ORDER BY FEE DESC, TD.HISTORY_ID DESC;