WITH RECURSIVE CTE AS (
    SELECT ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL

    UNION ALL

    SELECT D.ID, C.GENERATION + 1
    FROM ECOLI_DATA D
             JOIN CTE C
                  ON D.PARENT_ID = C.ID
)
SELECT ID
FROM CTE
WHERE GENERATION = 3
ORDER BY ID;
