SELECT ED3.ID
FROM ECOLI_DATA AS ED1
         JOIN ECOLI_DATA AS ED2
              ON ED1.ID = ED2.PARENT_ID
         JOIN ECOLI_DATA AS ED3
              ON ED2.ID = ED3.PARENT_ID
WHERE ED1.PARENT_ID is NULL
ORDER BY ED3.ID
