SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO
WHERE ITEM_ID IN (
    SELECT DISTINCT(T.ITEM_ID)
    FROM  ITEM_TREE T JOIN ITEM_INFO I ON(T.PARENT_ITEM_ID = I.ITEM_ID)
    WHERE RARITY = 'RARE'
)
ORDER BY ITEM_ID DESC
