WITH RECURSIVE GenerationCTE AS (
    SELECT ID, PARENT_ID, 1 AS GENERATION -- 재귀 초기값
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL

    UNION ALL

    SELECT E.ID, E.PARENT_ID, G.GENERATION + 1 -- 재귀
    FROM ECOLI_DATA E JOIN GenerationCTE G ON E.PARENT_ID = G.ID
)

SELECT COUNT(*) AS 'COUNT', GENERATION
FROM GenerationCTE
WHERE ID NOT IN (
    SELECT DISTINCT PARENT_ID
    FROM GenerationCTE
    WHERE PARENT_ID IS NOT NULL
)
GROUP BY GENERATION
ORDER BY GENERATION
