WITH BIGGEST AS(
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS BIGGEST_SIZE
FROM ECOLI_DATA
GROUP BY YEAR
    )

SELECT B.YEAR, (BIGGEST_SIZE - SIZE_OF_COLONY) AS YEAR_DEV, ID
FROM ECOLI_DATA E JOIN BIGGEST B ON YEAR(E.DIFFERENTIATION_DATE) = B.YEAR
ORDER BY YEAR, YEAR_DEV
