WITH MONTH AS(
    SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(HISTORY_ID) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE >= '2022-08-01' AND START_DATE <  '2022-11-01'
GROUP BY CAR_ID, MONTH),

    VALID_CAR AS(
SELECT CAR_ID
FROM MONTH
GROUP BY CAR_ID
HAVING SUM(RECORDS) >= 5)

SELECT *
FROM MONTH
WHERE CAR_ID IN (
    SELECT *
    FROM VALID_CAR)
ORDER BY MONTH, CAR_ID DESC
