SELECT AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(S.SALES * B.PRICE) AS TOTAL_SALES
FROM BOOK B JOIN AUTHOR A USING(AUTHOR_ID)
            JOIN BOOK_SALES S USING(BOOK_ID)
WHERE DATE_FORMAT(S.SALES_DATE, "%Y-%m") = '2022-01'
GROUP BY AUTHOR_ID, CATEGORY
ORDER BY B.AUTHOR_ID ASC, B.CATEGORY DESC;
