WITH FRONT AS (
    SELECT CODE
    FROM SKILLCODES
    WHERE CATEGORY = 'Front End'
)

SELECT DISTINCT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
FROM DEVELOPERS D, FRONT F
WHERE D.SKILL_CODE & F.CODE > 0
ORDER BY 1;
