WITH CAR AS (
    SELECT HISTORY_ID, CAR_ID, CAR_TYPE, DAILY_FEE, DATEDIFF(end_date, start_date) + 1 AS PERIOD,
           CASE WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90 THEN '90일 이상'
                WHEN DATEDIFF(end_date, start_date) + 1 >= 30 THEN '30일 이상'
                WHEN DATEDIFF(end_date, start_date) + 1 >= 7 THEN '7일 이상'
                ELSE 'NONE' END AS DURATION_TYPE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H LEFT JOIN CAR_RENTAL_COMPANY_CAR C USING(CAR_ID)
)

SELECT HISTORY_ID, ROUND(C.DAILY_FEE*(100 - IFNULL(P.DISCOUNT_RATE, 0)) * 0.01 * C.PERIOD) AS FEE
FROM CAR C LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P ON C.CAR_TYPE = P.CAR_TYPE AND C.DURATION_TYPE = P.DURATION_TYPE
WHERE C.CAR_TYPE = '트럭'
ORDER BY FEE DESC, HISTORY_ID DESC
